parameters:
  - name: imageTags
  - name: imageRepository
  - name: containerRegistryServiceConnection
  - name: vmImageName
  - name: useSelfHosted
    type: boolean

jobs:
  - job: Build
    displayName: Build job
    pool:
      ${{ if eq(parameters.useSelfHosted, true) }}:
        name: Default # Name of a pool.
        demands: docker
      ${{ else }}:
        vmImage: ${{ parameters.vmImageName }}
    steps:
    - task: Bash@3
      name: RunTests
      displayName: Run tests
      inputs:
        targetType: 'inline'
        script: |     
          echo 'placeholder for tests'
          
    - task: Docker@2
      displayName: Build and publish image to Azure Container Registry
      inputs:
        command: buildAndPush
        containerRegistry: ${{ parameters.containerRegistryServiceConnection }}
        repository: ${{ parameters.imageRepository }}
        dockerfile: $(Build.SourcesDirectory)/Dockerfile
        tags: ${{ parameters.imageTags }}
